version: "2"

networks:
  test-network:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - test-network
  kafka0:
    image: docker.io/bitnami/kafka:3
    ports:
      - '9092:9092'
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka0:29092,DOCKER://kafka0:9094,EXTERNAL://kafka0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka0:29092,DOCKER://localhost:9094,EXTERNAL://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,DOCKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - test-network
  kowl:
    image: quay.io/cloudhut/kowl:master
    environment:
      - KAFKA_BROKERS=kafka0:29092
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - kafka
    networks:
      - test-network

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local